version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"  # Publicly maps port 8080 on the host to Nginx in the container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mounts custom Nginx config
    depends_on:
      - app1
      - app2
      - app3

  app1:
    image: rate_telecall_apps
    command: ["streamlit", "run", "telecall_rate_builder.py", "--server.port=8501"]
    expose:
      - "8501"  # Internal port for Nginx to access

  app2:
    image: rate_telecall_apps
    command: ["streamlit", "run", "check.py", "--server.port=8502"]
    expose:
      - "8502"

  app3:
    image: rate_telecall_apps
    command: ["streamlit", "run", "upload.py", "--server.port=8503"]
    expose:
      - "8503"

  app_switcher:
    image: rate_telecall_apps
    command: ["streamlit", "run", "app_switcher.py", "--server.port=8504"]
    expose:
      - "8504"
