[server] 

maxUploadSize = 1024 
enableWebsocketCompression = true
maxMessageSize = 200  # Max message size in MB

[browser]
gatherUsageStats = true

[runner]
magicEnabled = false

[theme]
primaryColor = "#1e88e5"
backgroundColor = "#f0f2f6"
#primaryColor = "#FF6347"  # Example color (tomato red)
#backgroundColor = "#F0F0F0"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"
